### ISSUE TITLE
Sofirn sc21 pro show wrong firmware? 

### ISSUE THREAD

**Issue by DeddyIta** [ToyKeeper/anduril#41]
Thank you for your hard work!
I bought a sofirn sc21 pro, and it had on an old firmware from 2022. 
I updated my sc21 pro to the latest firmware 0632-2023-12-03. 
Everything works fine, but when I do 15 clicks to check the version, the flashlight show 0632-2023-10-31.
![Screenshot_20240118_230548_Cx File Explorer.jpg](https://github.com/ToyKeeper/anduril/assets/138687644/a5ea29c4-4ab3-42fd-b829-791387f4d2bf)

**Comment by ToyKeeper** [comment]
Are you sure you got the right file?  I flashed that file to a light just now, and version check show the 12-03 date code.

A quick way to tell is to use the battery check mode.  If it starts blinking out a value immediately, and gives 2 digits of precision, that's an older version.  If it pauses for a moment before the readout, then gives 3 digits of precision, that's 2023-12-03 or later.

**Comment by DeddyIta** [comment]
Thanks for the reply ToyKeeper. I'm sure I've tried several times to download the latest anduril version from the repo and use the hex file specific to the sofirn sc21 pro. I also tried the battery reading and it gives me 2 digits.I don't have any other anduril folders in my smartphone other than the one of the latest version.

**Comment by DeddyIta** [comment]
I tried to download the folder again, and proceeded to flash the flashlight firmware again. Now show the right version. Thank you.
