### ISSUE TITLE
When using aux LEDs as channels, the lowest mode turns the LEDs off

### ISSUE THREAD

**Issue by aslotnick** [ToyKeeper/anduril#65]
This applies when using a light with aux LEDs such as the ts10 or ts10-rgb.

Steps to reproduce:
* after factory reset, enter advanced mode. On ts10, smooth ramp floor level will be 1/150.
* using 9H from on, activate an aux LED as a channel.
* Using 3C from on, select the now active aux as the active channel.
* Select the floor level. The aux LEDs will be off.

My expectation is that when using an aux LED as an active channel, the light being on at level 1 should result in the aux LEDs being active, but this doesn't seem to be the case. When ramping to any other level (2+), the aux LEDs are on at the high level.

**Comment by SiteRelEnby** [comment]
Fix pending: https://github.com/ToyKeeper/anduril/pull/47

**Comment by ToyKeeper** [comment]
Fixed by 5a69f495bf773d825468ab8ce74b79b3d3de0dc5.
