### ISSUE TITLE
Request: Remove strobes/lightning from "Extended Simple" UI

### ISSUE THREAD

**Issue by lukestein** [ToyKeeper/anduril#85]
The readme suggests this may happen. I'm just putting in my vote/request to have this as a way to make some vaguely "kid safe" (or even just "sleepy middle of the night-safe" mode) where I can prevent getting anything too bright.

> It is likely that strobe/mood modes will be removed from Extended Simple UI in the future, for safety reasons, or maybe have already been removed. But that doesn't help with older firmware, so be careful.

**Comment by ToyKeeper** [comment]
Yeah, I think having those enabled in simple mode was a mistake.
